In [175]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [176]:
train = pd.read_csv('/Users/apricuz/Data/2021-2022 NBA Player Stats - Regular.csv')
test = pd.read_csv('/Users/apricuz/Data/2022-2023 NBA Player Stats - Regular.csv')

In [177]:
train.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'AS'],
      dtype='object')

In [178]:
predictors = ['MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

In [179]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(train[predictors], train['AS'])
predictions = model.predict(test[predictors])

In [180]:
predictions

array([ 3.55140615e-02, -2.78393073e-02,  2.28708464e-01, -2.50051535e-02,
        4.72208939e-02,  3.09904345e-03,  5.43720036e-02, -3.28868069e-02,
        7.17758461e-02,  1.14049387e-01,  1.96749006e-02,  3.99682983e-02,
        5.88210787e-01, -2.94927247e-02,  1.22532649e-01,  5.75297394e-02,
        2.00296813e-02,  4.97359489e-02, -5.39437877e-02,  4.59135209e-02,
        1.26085650e-01, -9.59550483e-03,  5.53020938e-02,  1.33048758e-02,
        2.63436163e-01, -4.55863645e-04,  1.52925208e-02,  3.67467860e-02,
        2.71659879e-01,  2.41177372e-01, -1.95334044e-02, -8.58610840e-02,
        2.16204413e-01,  8.53083405e-02,  1.20614528e-01, -1.01503579e-02,
        3.02366022e-02, -8.36680781e-02, -2.37283341e-03,  6.23910277e-02,
       -1.40108819e-02, -9.75058137e-03, -8.54158844e-03, -1.38796640e-02,
        2.86620373e-01, -1.92665528e-02, -4.43415970e-03, -1.50670280e-02,
       -4.61911517e-02, -3.90184249e-02, -4.30030303e-02, -6.90969453e-02,
       -4.65576493e-02,  

In [181]:
predictions[0]

0.0355140614540773

In [182]:
for i in range(predictions.shape[0]):
    if predictions[i] > 0.3:
        predictions[i] = 1
    else:
        predictions[i] = 0

In [183]:
predictions

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [184]:
predictions = pd.DataFrame(predictions, columns = ["predictions"])

In [185]:
predictions

predictions
0            0.0
1            0.0
2            0.0
3            0.0
4            0.0
..           ...
674          0.0
675          1.0
676          0.0
677          0.0
678          0.0

[679 rows x 1 columns]

In [186]:
combination = pd.concat([test[["Player", "PTS", "AS"]], predictions], axis=1)

In [187]:
combination

Player   PTS  AS  predictions
0    Precious Achiuwa   9.2   0          0.0
1        Steven Adams   8.6   0          0.0
2         Bam Adebayo  20.4   1          0.0
3        Ochai Agbaji   7.9   0          0.0
4        Santi Aldama   9.0   0          0.0
..                ...   ...  ..          ...
674    Thaddeus Young   4.4   0          0.0
675        Trae Young  26.2   0          1.0
676    Omer Yurtseven   4.4   0          0.0
677       Cody Zeller   6.5   0          0.0
678       Ivica Zubac  10.8   0          0.0

[679 rows x 4 columns]

In [188]:
combination.sort_values("predictions", ascending=False).head(49)

Player   PTS  AS  predictions
175             Kevin Durant  29.7   1          1.0
198             De'Aaron Fox  25.0   1          1.0
427         Donovan Mitchell  28.3   1          1.0
245             James Harden  21.0   0          1.0
160              Luka Doncic  32.4   1          1.0
209  Shai Gilgeous-Alexander  31.4   1          1.0
318             Nikola Jokic  24.5   1          1.0
239        Tyrese Haliburton  20.7   1          1.0
79             Mikal Bridges  26.1   0          1.0
150            DeMar DeRozan  24.5   1          1.0
392          Lauri Markkanen  25.6   1          1.0
306             LeBron James  28.9   1          1.0
609       Karl-Anthony Towns  20.8   0          1.0
141            Anthony Davis  25.9   0          1.0
139            Stephen Curry  29.4   1          1.0
549         Domantas Sabonis  19.1   1          1.0
295             Kyrie Irving  27.0   1          1.0
294             Kyrie Irving  27.1   1          1.0
293             Kyrie Irving  27.1   1          1.0
292           Brandon Ingram  24.7   0          1.0
63          Bojan Bogdanovi?  21.6   0          1.0
373           Damian Lillard  32.2   1          1.0
206              Paul George  23.8   1          1.0
12     Giannis Antetokounmpo  31.1   1          1.0
664          Zion Williamson  26.0   1          1.0
100             Jimmy Butler  22.9   0          1.0
675               Trae Young  26.2   0          1.0
502       Kristaps Porzi??is  23.2   0          1.0
514            Julius Randle  25.1   1          1.0
360              Zach LaVine  24.8   0          1.0
176             Kevin Durant  26.0   1          1.0
435                Ja Morant  26.2   1          1.0
184              Joel Embiid  33.1   1          1.0
174             Kevin Durant  29.1   1          1.0
66              Devin Booker  27.8   0          1.0
369            Kawhi Leonard  23.8   0          1.0
590             Jayson Tatum  30.1   1          1.0
497             Jordan Poole  20.4   0          1.0
447             Mike Muscala   5.9   0          0.0
463            Kendrick Nunn   7.1   0          0.0
442          Dejounte Murray  20.5   0          0.0
449           Svi Mykhailiuk   1.6   0          0.0
450           Svi Mykhailiuk  10.6   0          0.0
443             Jamal Murray  20.0   0          0.0
444            Keegan Murray  12.2   0          0.0
467             Jordan Nwora   8.7   0          0.0
466             Jusuf Nurki?  13.3   0          0.0
465            Kendrick Nunn   7.5   0          0.0
451          Larry Nance Jr.   6.8   0          0.0

In [189]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [190]:
print('mean squared error: ', mean_squared_error(test['AS'], predictions))
print('mean absolute error: ', mean_absolute_error(test['AS'], predictions))

mean squared error:  0.027982326951399118
mean absolute error:  0.027982326951399118


In [191]:
combination.to_csv('result.csv', index = False)

In [192]:
combination.sort_values("AS", ascending=False).head(49)

Player   PTS  AS  predictions
175             Kevin Durant  29.7   1          1.0
150            DeMar DeRozan  24.5   1          1.0
198             De'Aaron Fox  25.0   1          1.0
373           Damian Lillard  32.2   1          1.0
160              Luka Doncic  32.4   1          1.0
206              Paul George  23.8   1          1.0
239        Tyrese Haliburton  20.7   1          1.0
318             Nikola Jokic  24.5   1          1.0
565            Pascal Siakam  24.2   1          0.0
209  Shai Gilgeous-Alexander  31.4   1          1.0
427         Donovan Mitchell  28.3   1          1.0
392          Lauri Markkanen  25.6   1          1.0
306             LeBron James  28.9   1          1.0
139            Stephen Curry  29.4   1          1.0
300        Jaren Jackson Jr.  18.6   1          0.0
549         Domantas Sabonis  19.1   1          1.0
295             Kyrie Irving  27.0   1          1.0
294             Kyrie Irving  27.1   1          1.0
85              Jaylen Brown  26.6   1          0.0
273             Jrue Holiday  19.3   1          0.0
293             Kyrie Irving  27.1   1          1.0
12     Giannis Antetokounmpo  31.1   1          1.0
2                Bam Adebayo  20.4   1          0.0
664          Zion Williamson  26.0   1          1.0
184              Joel Embiid  33.1   1          1.0
179          Anthony Edwards  24.6   1          0.0
176             Kevin Durant  26.0   1          1.0
174             Kevin Durant  29.1   1          1.0
435                Ja Morant  26.2   1          1.0
590             Jayson Tatum  30.1   1          1.0
514            Julius Randle  25.1   1          1.0
441          Trey Murphy III  14.5   0          0.0
461            Jaylen Nowell  10.8   0          0.0
462          Frank Ntilikina   2.9   0          0.0
463            Kendrick Nunn   7.1   0          0.0
464            Kendrick Nunn   6.7   0          0.0
459             Nerlens Noel   2.3   0          0.0
465            Kendrick Nunn   7.5   0          0.0
440             Monte Morris  10.3   0          0.0
466             Jusuf Nurki?  13.3   0          0.0
467             Jordan Nwora   8.7   0          0.0
468             Jordan Nwora   6.0   0          0.0
460             Nerlens Noel   1.0   0          0.0
447             Mike Muscala   5.9   0          0.0
458             Nerlens Noel   2.1   0          0.0
452          Andrew Nembhard   9.5   0          0.0
446             Mike Muscala   6.2   0          0.0
449           Svi Mykhailiuk   1.6   0          0.0
445             Mike Muscala   6.1   0          0.0

In [193]:
from sklearn.metrics import confusion_matrix

In [194]:
confusion_matrix(combination['AS'], combination['predictions'])

array([[635,  13],
       [  6,  25]])